import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../src/components/Header";
import Footer from "../src/components/Footer";
import DropDownSearch from "../src/components/DropDownSearch";
import CardType1 from "../src/components/Cards/CardType1";
import CardType2 from "../src/components/Cards/CardType2";
import CardType3 from "../src/components/Cards/CardType3";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="">
        <DropDownSearch />
        <CardType1 />
        <CardType2 />
        <CardType3 />
      </main>

      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  );
};

export default Home;
